dist: bionic
addons:
  apt:
    packages:
      - genisoimage
      - gnupg2
      - qemu-utils
      - qemu-kvm
      - rpm
      - systemd-container
matrix:
  include:
    - name: fedora_31
      arch: amd64
    - name: fedora_32
      arch: amd64

language: generic
script:
  - true
